# Generated by Django 5.2.8 on 2025-12-15 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_school_school_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Complete name of the school administrator', max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Primary email for login and communication', max_length=254, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(help_text='10-digit mobile number', max_length=10, verbose_name='Phone Number')),
                ('profile_photo', models.ImageField(blank=True, help_text='Profile picture (max 2MB)', null=True, upload_to='school_admin_photos/', verbose_name='Profile Photo')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, help_text='Complete residential address', null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('pincode', models.CharField(blank=True, help_text='6-digit PIN code', max_length=6, null=True, verbose_name='PIN Code')),
                ('account_status', models.CharField(choices=[('pending', 'Pending - Awaiting First Login'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20, verbose_name='Account Status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this admin account is active', verbose_name='Is Active')),
                ('temporary_password', models.CharField(blank=True, help_text='Hashed temporary password for first login', max_length=128, null=True, verbose_name='Temporary Password')),
                ('password_changed', models.BooleanField(default=False, help_text='Whether user has changed from temporary password', verbose_name='Password Changed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_login', models.DateTimeField(blank=True, help_text='Timestamp of first login', null=True, verbose_name='First Login')),
                ('last_login', models.DateTimeField(blank=True, help_text='Timestamp of most recent login', null=True, verbose_name='Last Login')),
                ('created_by', models.ForeignKey(help_text='Super Admin who created this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_school_admins', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('school', models.ForeignKey(help_text='School that this admin manages', on_delete=django.db.models.deletion.CASCADE, related_name='school_admins', to='schools.school', verbose_name='Assigned School')),
                ('user', models.OneToOneField(help_text='Linked user account for authentication', on_delete=django.db.models.deletion.CASCADE, related_name='school_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'School Admin',
                'verbose_name_plural': 'School Admins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='school_admi_email_805d14_idx'), models.Index(fields=['school'], name='school_admi_school__2d80c3_idx'), models.Index(fields=['account_status'], name='school_admi_account_fd61d9_idx')],
            },
        ),
    ]
