# Generated by Django 5.2.4 on 2025-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last password change', null=True, verbose_name='Last Password Change'),
        ),
    ]
