# Generated by Django 5.2.4 on 2025-12-27 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='coordinator/profile_photos/')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('designation', models.CharField(choices=[('Program Coordinator', 'Program Coordinator'), ('Project Coordinator', 'Project Coordinator')], max_length=50)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(choices=[('Operations', 'Operations'), ('Education', 'Education'), ('Project Management', 'Project Management'), ('Others', 'Others')], max_length=50)),
                ('total_experience', models.CharField(max_length=100)),
                ('program_management_exp', models.CharField(blank=True, max_length=100, null=True)),
                ('education_exp', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_organizations', models.TextField(blank=True, null=True)),
                ('languages_known', models.CharField(max_length=255)),
                ('certifications', models.CharField(blank=True, max_length=500, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='coordinator/resumes/')),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('official_email', models.EmailField(max_length=254, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('current_address', models.TextField()),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('id_proof', models.CharField(blank=True, max_length=50, null=True)),
                ('address_proof', models.CharField(blank=True, max_length=50, null=True)),
                ('police_verification', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('passport_photo_uploaded', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('contract_uploaded', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('pan_aadhar_linked', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('nda_signed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('program_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('zone_assigned', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_region', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('login_role', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Contract', 'Contract'), ('Consultant', 'Consultant')], max_length=20)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('bank_proof', models.FileField(blank=True, null=True, upload_to='coordinator/bank_proofs/')),
                ('strength_areas', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('work_style', models.CharField(blank=True, choices=[('Field', 'Field'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=20, null=True)),
                ('tools_comfortable', models.CharField(blank=True, max_length=500, null=True)),
                ('achievements', models.TextField(blank=True, null=True)),
                ('career_aspirations', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coordinators', to=settings.AUTH_USER_MODEL)),
                ('schools_assigned', models.ManyToManyField(blank=True, related_name='program_coordinators', to='schools.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_coordinator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Program Coordinator',
                'verbose_name_plural': 'Program Coordinators',
                'ordering': ['-created_at'],
            },
        ),
    ]
