# Generated by Django 5.2.4 on 2025-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
