# Generated by Django 5.2.4 on 2025-12-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_school_admin'),
        ('superadmin', '0005_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.school'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
