# Generated by Django 5.2.4 on 2025-12-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_lesson_lessonresource_lessonvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
