# Generated by Django 5.2.8 on 2026-03-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=2)),
                ('color', models.CharField(choices=[('teal', 'Teal'), ('purple', 'Purple'), ('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_pillars', to='competencies.pillar')),
            ],
            options={
                'ordering': ['sp_number'],
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('Foundational', 'Foundational — Class 1–2'), ('Preparatory', 'Preparatory — Class 3–5'), ('Middle', 'Middle — Class 6–8'), ('Secondary', 'Secondary — Class 9–12')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='competencies.subpillar')),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'ordering': ['sub_pillar__sp_number', 'code'],
            },
        ),
    ]
