# Generated by Django 5.2.8 on 2026-03-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0002_seed_pillars_subpillars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('primary_competencies', models.ManyToManyField(blank=True, related_name='primary_profiles', to='competencies.competency')),
                ('secondary_competencies', models.ManyToManyField(blank=True, related_name='secondary_profiles', to='competencies.competency')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
