# Generated by Django 5.2.8 on 2026-03-12 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0004_seed_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('Capstone', 'Capstone'), ('Formative', 'Formative'), ('Summative', 'Summative')], default='Capstone', max_length=20)),
                ('grade', models.CharField(choices=[('Foundational', 'Foundational — Class 1–2'), ('Preparatory', 'Preparatory — Class 3–5'), ('Middle', 'Middle — Class 6–8'), ('Secondary', 'Secondary — Class 9–12')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('assessment_type', models.CharField(choices=[('Written Assignment', 'Written Assignment'), ('Presentation', 'Presentation'), ('Peer Review', 'Peer Review'), ('Lab Report', 'Lab Report')], default='Written Assignment', max_length=30)),
                ('output_descriptor', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='competencies.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_mappings', to='competencies.assessment')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mappings', to='competencies.competency')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('assessment', 'competency')},
            },
        ),
    ]
