# Generated by Django 5.2.8 on 2026-03-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0005_project_assessment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='rubric_file',
            field=models.FileField(blank=True, null=True, upload_to='rubrics/'),
        ),
    ]
