# Generated by Django 5.2.8 on 2026-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0006_add_rubric_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='additional_instructions',
            field=models.TextField(blank=True, help_text='Additional instructions for the teacher'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='placement_after_challenge',
            field=models.PositiveSmallIntegerField(blank=True, help_text='After Challenge #', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Life Form', 'Life Form'), ('Machines & Materials', 'Machines & Materials'), ('Human Services', 'Human Services'), ('Plug In', 'Plug In'), ('Final Project', 'Final Project')], default='Capstone', max_length=20),
        ),
    ]
