# Generated by Django 5.2.8 on 2026-03-14 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0009_add_student_assessment_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linked_project',
            field=models.ForeignKey(blank=True, help_text='Only for Plug-In type: select the Project this Plug-In belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugins', to='competencies.project'),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score 1–4', null=True),
        ),
    ]
