# Generated by Django 5.2.4 on 2026-03-18 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0010_add_plugin_linked_project'),
        ('student', '0001_move_student_from_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order of this project in the year (1, 2, 3, 4). Used for Annual Passport — latest score wins.', null=True),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score 1–10', null=True),
        ),
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_3_profiles', models.JSONField(default=list)),
                ('top_5_competencies', models.JSONField(default=list)),
                ('skills_to_work_on', models.JSONField(default=list)),
                ('all_competency_scores', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('is_outdated', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='competencies.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='student.student')),
            ],
            options={
                'unique_together': {('student', 'project')},
            },
        ),
    ]
