# Generated by Django 5.2.4 on 2026-03-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0012_studentprojectfeedback'),
        ('lms', '0001_move_lessons_from_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='competency',
            field=models.ForeignKey(blank=True, help_text='Competency this lesson belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='competencies.competency', verbose_name='Competency'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Sub-Pillar this lesson falls under', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='competencies.subpillar', verbose_name='Module / Category'),
        ),
    ]
