# Generated by Django 5.2.4 on 2025-12-12 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_admin',
            field=models.ForeignKey(blank=True, help_text='Assign a School Admin to manage this school', limit_choices_to={'role': 'SCHOOL_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_school', to=settings.AUTH_USER_MODEL, verbose_name='School Admin'),
        ),
    ]
