# Generated by Django 5.2.4 on 2025-12-22 06:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_school_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1', 'Standard 1'), ('2', 'Standard 2'), ('3', 'Standard 3'), ('4', 'Standard 4'), ('5', 'Standard 5'), ('6', 'Standard 6'), ('7', 'Standard 7'), ('8', 'Standard 8'), ('9', 'Standard 9'), ('10', 'Standard 10'), ('11', 'Standard 11'), ('12', 'Standard 12')], help_text='Grade level of the class', max_length=2, verbose_name='Grade / Standard')),
                ('division', models.CharField(help_text='Division/Section of the class (e.g., A, B, C)', max_length=5, verbose_name='Division')),
                ('class_name', models.CharField(help_text='Auto-generated class name (e.g., Std 9A)', max_length=50, verbose_name='Class Name')),
                ('class_code', models.CharField(help_text='Unique identifier for this class', max_length=50, unique=True, verbose_name='Class Code')),
                ('academic_year', models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027')], default='2024-2025', help_text='Academic year for this class', max_length=9, verbose_name='Academic Year')),
                ('total_sessions', models.PositiveIntegerField(default=48, help_text='Total number of sessions for this class', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Total Sessions')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this class is active', verbose_name='Class Status')),
                ('student_visibility', models.BooleanField(default=True, help_text='Show this class to assigned students', verbose_name='Student Visibility')),
                ('parent_visibility', models.BooleanField(default=False, help_text='Show this class to connected parents', verbose_name='Parent Visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('school', models.ForeignKey(help_text='School this class belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.school', verbose_name='School')),
                ('thinking_coach', models.ForeignKey(blank=True, help_text='Assigned thinking coach for this class', limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to=settings.AUTH_USER_MODEL, verbose_name='Thinking Coach')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['school', 'grade', 'division'],
                'indexes': [models.Index(fields=['class_code'], name='schools_cla_class_c_e51e0e_idx'), models.Index(fields=['school', 'academic_year'], name='schools_cla_school__671e7a_idx')],
                'unique_together': {('school', 'grade', 'division', 'academic_year')},
            },
        ),
    ]
